# Generated by Django 6.0.3 on 2026-07-12 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('man', 'اقایون'), ('women', 'خانوم ها')], max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'سالن',
                'verbose_name_plural': 'سالن\u200cها',
            },
        ),
        migrations.CreateModel(
            name='MainHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'اطلاعات تالار',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'آیتم منو',
                'verbose_name_plural': 'منوی اصلی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SelfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveBigIntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'سلف سرویس',
                'verbose_name_plural': 'سلف سرویس',
            },
        ),
        migrations.CreateModel(
            name='SpecialMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveBigIntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'منوی ویژه',
                'verbose_name_plural': 'منوهای ویژه',
            },
        ),
        migrations.CreateModel(
            name='HallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='halls/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.hall')),
            ],
            options={
                'verbose_name': 'عکس سالن',
                'verbose_name_plural': 'عکس\u200cهای سالن',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MainHallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mainhall/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.mainhall')),
            ],
            options={
                'verbose_name': 'عکس تالار',
                'verbose_name_plural': 'عکس\u200cهای تالار',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice_type', models.CharField(choices=[('none', 'بدون برنج'), ('pakistani', 'با برنج پاکستانی'), ('iranian', 'با برنج ایرانی')], max_length=15)),
                ('price', models.PositiveBigIntegerField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rice_options', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'گزینه\u200cی برنج',
                'verbose_name_plural': 'گزینه\u200cهای برنج',
                'ordering': ['order'],
                'unique_together': {('menu_item', 'rice_type')},
            },
        ),
    ]
