# Generated by Django 6.0.3 on 2026-07-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.PositiveIntegerField(default=100, verbose_name='تعداد مهمانان')),
                ('date', models.DateField(verbose_name='تاریخ مراسم')),
                ('shift', models.CharField(choices=[('noon', 'ظهر'), ('night', 'شب')], max_length=10, verbose_name='شیفت')),
                ('customer_name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('cancelled', 'لغو شده')], default='pending', max_length=15, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('notes', models.TextField(blank=True, default='', verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'unique_together': {('date', 'shift')},
            },
        ),
    ]
